---
- hosts: weatherapp
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu disco stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install docker-compose
      apt: name=docker-compose state=latest

    - name: Copy weatherapp backend
      copy:
        src: backend
        dest: .

    - name: Copy weatherapp frontend
      copy:
        src: frontend
        dest: .

    - name: Copy weatherapp docker-compose.yml
      copy:
        src: "docker-compose.yml"
        dest: "docker-compose.yml"

    - name: Tear down app
      docker_compose:
        project_src: .
        state: absent

    - name: Run app
      docker_compose:
        project_src: .
        build: yes
        state: present
        recreate: always
        restarted: yes

    - name: Install nginx
      apt: name=nginx state=latest

    - name: Copy weatherapp nginx site
      copy:
        src: weatherapp
        dest: /etc/nginx/sites-available/default

    - name: Restart service nginx
      service:
        name: nginx
        state: restarted
