version: "3.6"

services:
  backend:
    build: backend
    ports:
      - "9000:9000"
    networks:
      - app
    environment:
      APPID: "ENTER YOUR APPID"
  frontend:
    build: frontend
    ports:
      - "8000:8000"
    networks:
      - app
    environment:
      ENDPOINT: "https://weather.matejc.com/api"
    depends_on:
      - backend

networks:
  app:
